Add missing collection methods
vavr-io/vavr-kotlin pull request #19
Opened 2020-10-20 21:51 UTC by mandrean

This PR adds missing collection methods, most importantly `Iterable<T>.toVavrSet()`, but also some others that might for example have a `.toVavrList()` but not one for `Set` etc.

It also improves the kdocs and does some general cleanup using `ktlint`.

Best reviewed commit by commit, as they are very atomic and descriptive in what they do.

2020-10-22 02:40 UTC, ruslansennov requested changes
Thanks @mandrean 
Just two comments on the kdocs

2020-10-22 02:40 UTC, ruslansennov commented on src/main/kotlin/io/vavr/kotlin/Collections.kt
> + * Converts a Kotlin [Sequence] into a Vavr [List].
into Set

2020-10-22 02:40 UTC, ruslansennov commented on src/main/kotlin/io/vavr/kotlin/Collections.kt
> + * Creates a Vavr [TreeSet] from a series of Kotlin [Pair]s.
of the given elements

2020-10-23 09:59 UTC, mandrean commented
Thanks for the quick feedback @ruslansennov!

Pushed a new commit fixing the typos

2020-10-26 09:23 UTC, ruslansennov approved these changes

2020-10-26 09:23 UTC, merged